account_id = "f6db10971f58fd9d4f6f9f646d8b21df"
name = "cloudhack"
type = "webpack"
workers_dev = true
site = { bucket = "./public" }

[env.production]
# The ID of the domain to deploying to
zone_id = "05d62767c852f1432e3886482a4be3af"

# The route pattern your Workers application will be served at
route = "cloudhacktech.cf/*"
